### ISSUE TITLE
gpapi.googleplay.LoginError: 'Unexpected behaviour, probably expired token'

### ISSUE THREAD

**Issue by TheT3ngu** [matlink/gplaycli#122]
Hey guys,

just installed gplaycli on my ubuntu server, and whenever I search for packages, I get this error. For example:
```gplaycli -s 'whatsapp'
Traceback (most recent call last):
  File "/usr/local/bin/gplaycli", line 9, in <module>
    load_entry_point('GPlayCli==3.9', 'console_scripts', 'gplaycli')()
  File "/usr/local/lib/python3.5/dist-packages/gplaycli/gplaycli.py", line 527, in main
    cli.search(list(), args.search_string, nb_results, not args.paid)
  File "/usr/local/lib/python3.5/dist-packages/gplaycli/gplaycli.py", line 365, in search
    results = self.raw_search(results_list, search_string, nb_results)
  File "/usr/local/lib/python3.5/dist-packages/gplaycli/gplaycli.py", line 361, in raw_search
    return self.playstore_api.search(search_string, nb_result=nb_results)
  File "/usr/local/lib/python3.5/dist-packages/gpapi/googleplay.py", line 263, in search
    raise LoginError('Unexpected behaviour, probably expired '
gpapi.googleplay.LoginError: 'Unexpected behaviour, probably expired token'```

System configuration:
```lsb_release -a
No LSB modules are available.
Distributor ID:	Ubuntu
Description:	Ubuntu 16.04.3 LTS
Release:	16.04
Codename:	xenial
```

gplaycli version:
```
gplaycli -v
[INFO] GPlayCli version 3.9 [Python3.5.2] 
[INFO] Configuration file is /home/tengu/.config/gplaycli/gplaycli.conf
[INFO] Using cached token.
[INFO] Using token to connect to API
[INFO] Starting new HTTPS connection (1): android.clients.google.com
```

content of my /home/tengu/.config/gplaycli/gplaycli.conf:
```
[Credentials]
gmail_address=<mygmail>
gmail_password=<mygmailpassword>
#keyring_service=gplaycli
android_ID=3d716411bf8bc802
language=de_DE
token=True
token_url=https://matlink.fr/token/email/gplaycliacc@gmail.com

[Cache]
token=~/.cache/gplaycli/token
```

Thanks for any hint!

**Comment by matlink** [comment]
Get a new version of `gplaycli.conf` here: https://github.com/matlink/gplaycli/blob/master/gplaycli.conf
and see if it resolves your issue.

**Comment by matlink** [comment]
I've pushed a quick fix (5482f3f5a9852364284285aa1e10edd01243f947) which should handle that exception.

**Comment by TheT3ngu** [comment]
Hey matlink,
thanks for the quick response and the bugfix! But I'm not quite sure what to do with this. I updated gplaycli via `sudo pip3 install gplaycli --upgrade` but the error still occurs. Am I doing it right?

**Comment by matlink** [comment]
Well in fact no because I didn't pushed it to pypi.
Use instead `sudo pip install --upgrade https://github.com/matlink/gplaycli/archive/master.zip`

**Comment by TheT3ngu** [comment]
Thanks, that's it - everything works now!
